name: Run reproducer on each commit
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 17
    - uses: gradle/gradle-build-action@v2
      with:
        arguments: test
    - name: Show test output
      if: always()
      run: cat build/test-results/test/TEST-org.example.gradle.junit.xml.limitations.FailingParameterizedTest.xml
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/test-results/**
